doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ByteSpin\ConsoleCommandSchedulerBundle:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/vendor/bytespin/console-command-scheduler-bundle/src/Entity'
                        prefix: ByteSpin\ConsoleCommandSchedulerBundle\Entity
                        alias: ByteSpin\ConsoleCommandSchedulerBundle

